### ISSUE TITLE
display-buffer-in-side-window: Symbol’s function definition is void: a-list

### ISSUE THREAD

**Issue by jasoncyu** [alphapapa/org-sidebar#1]
Hello, when running the interactive function `org-sidebar`, I got the error 
`display-buffer-in-side-window: Symbol’s function definition is void: a-list`. Where should I be getting this function from?

Thanks!

**Comment by alphapapa** [comment]
Hi Jason,

Thanks for catching this.  I just pushed a fix that removes those calls for now.  The function is from https://github.com/plexus/a.el, which is a great package, but few people have it installed, because few packages depend on it.  And I forgot to add the dependency here.  It should work now.
