### ISSUE TITLE
Projects contain too many same todo headlines

### ISSUE THREAD

**Issue by llcc** [alphapapa/org-sidebar#20]
Me again. Thanks again.

I manage several projects in one org file, and those projects own almost some same subtasks as below. Those subtasks will be collected into the todo tree buffer several times after calling `org-sidebar-toggle`, which could cause some visual problems sometimes. You can confirm the image below. 

Do you probably think it is good to offer any customized option to add some indentation to make its hira

```org
#+title: Project notebooks

* TODO Project 1
** TODO Child Task 1
*** TODO a more smaller task
** TODO Child Task 2
*** TODO a more smaller task
** TODO Child Task 3
*** TODO a more smaller task

* TODO Project 2
** TODO Child Task 1
*** TODO a more smaller task
** TODO Child Task 2
*** TODO a more smaller task
** TODO Child Task 3
*** TODO a more smaller task

* Some notes
* Footnotes
```

![image](https://user-images.githubusercontent.com/3996879/77753514-fce70980-706c-11ea-90e5-dd35f3ac1f66.png)

**Comment by alphapapa** [comment]
Indenting the headings according to their depth could be helpful in some cases, however if the headings are not in file order, or if their parent headings are not displayed, they would not be displayed correctly, i.e. according to the outline structure.  So that probably would not be a good idea.

Note also that `org-sidebar` uses `org-ql-view` now, so this functionality is part of `org-ql`, not `org-sidebar`.

If you need a structured outline view, you should probably use, e.g. `org-sidebar-tree`, so it will correctly reflect the outline structure.

Alternatively, a more specific sidebar query that displays more specifically relevant tasks could be useful.  Try pressing `v` in the sidebar item buffer and you can edit the query.
