### ISSUE TITLE
Cycling causes freeze/crash

### ISSUE THREAD

**Issue by shaund** [alphapapa/org-sidebar#22]
To replicate, open org-sidebar-tree, create a new heading in main document, write some text under it, switch to the sidebar, then visibility-cycle with Shift-Tab. Emacs will freeze.

**Comment by alphapapa** [comment]
Works for me.

**Comment by alphapapa** [comment]
If you can reproduce this, please provide more details and a test case.  Otherwise I must assume it's unique to your Emacs config.

**Comment by tams** [comment]
+1 on custom configs causing this. After adding the package, reloading the config with `doom/reload` of [doom-emacs](https://github.com/hlissner/doom-emacs) (along with some package interactions it might involve) seems to be one way to trigger this.

No big deal, the issue is gone after a fresh launch.
