### ISSUE TITLE
Can't navigate sidebar tree with <return>

### ISSUE THREAD

**Issue by arozbiz** [alphapapa/org-sidebar#43]
I'm using org-sidebar in a new Doom installation and am having a problem navigating in the org-sidebar-tree. When I navigate in the tree and press <return>, nothing happens. But when I click with my mouse, navigation occurs normally. I've enabled command-log-mode to see what's happening, and when I enter <return> the "+org/dwim-at-point" function runs (and doesn't do anything). When I click with my mouse, "org-sidebar-tree-jump-mouse" runs. If I go into the tree sidebar and manually (M-x) run "org-sidebar-tree-jump" I get the desired result. So do I need to specially bind that function to <return>? And if so how do I do that only in the tree sidebar? Looking at the org-sidebar.el source at line 370 (https://github.com/alphapapa/org-sidebar/blob/master/org-sidebar.el), it looks like <return> should already be bound to org-sidebar-tree-jump? 

I'm new to Emacs, so apologies in advance for silly questions.

**Comment by alphapapa** [comment]
Hi,

It sounds like the problem is caused by Doom, so you should probably ask on the Doom Discord channel.

**Comment by arozbiz** [comment]
Got it. Thanks for getting back to me.

**Comment by dlukes** [comment]
Sorry to revive this, but did you end up solving this, @arozbiz? If so, would you mind sharing here? It might be helpful for others, including myself, it's easier to find the solution here than in Discord history :)

**Comment by dlukes** [comment]
So I think this may be caused by the intricacies of Evil, which org-sidebar doesn't support out-of-the-box? I don't know what proper integration would look like (just noticed that e.g. Treemacs has a special module for Evil support), I tried the following, but unfortunately, it also affects the bindings in the original (full) buffer for some reason, even though it uses `evil-normal-state-local-map`:

```elisp
(defun org-sidebar-evil-bindings ()
  (define-key! evil-normal-state-local-map
    "RET" #'org-sidebar-tree-jump
    "<return>" #'org-sidebar-tree-jump))
(add-hook 'org-sidebar-window-after-display-hook #'org-sidebar-evil-bindings)
```

The workaround I'll probably use is to put the sidebar tree buffer in Emacs state with `M-x evil-emacs-state`, bound to `C-z` in Doom with Evil by default. Then RET seems to work.

**Comment by dlukes** [comment]
Right, that makes sense :)

**Comment by freeo** [comment]
For the next person ending up in this issue:

Add to `config.el` and reload:
```
(after! org-sidebar
  (evil-set-initial-state 'org-sidebar-mode 'emacs))

(setq org-sidebar-tree-jump-fn 'org-sidebar-tree-jump-source)
```
First two lines fix the actual problem: org-sidebar is loaded in evil's normal mode. Fix provided by doom's author in discord.

3rd line to actually jump to the source file - this is the more sensible default, imho.
