### ISSUE TITLE
Adding other agenda-files in the sidebar-tree

### ISSUE THREAD

**Issue by proudot** [alphapapa/org-sidebar#56]
Hey, thanks for your wonderful plugin, as always. Your work is a huge help for the emacs community. 

I was wondering if org-sidebar-tree could be used to add other files, like for example the agenda-files along with the current buffer. This is remotely inspired from  sublime text that has a very intuitive way to handle the navigation pane. 

Cheers!

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words, I'm glad it's useful to you.

As currently implemented, that would not be possible, because the tree buffer is just a cloned indirect buffer of the buffer it's showing.  You might want to look at some other packages that provide similar functionality, like Speedbar (built-in to Emacs), Treemacs, etc.

**Comment by proudot** [comment]
OK, makes sense, thanks for the reply :).
