### ISSUE TITLE
hard to navigate without having buffer end up showing only right part of TODO

### ISSUE THREAD

**Issue by maxandersen** [alphapapa/org-sidebar#9]
i'm trying to figure out how to use  org-sidebar the best and for some reason I tend to up with the content scrolled all the way to the right like this:

![2019-09-30_11-50-36](https://user-images.githubusercontent.com/54129/65868443-89dc2f00-e378-11e9-8875-ce8ea3cc7b10.png)

rather than showing the more useful but also quite tight "left" side of the content:

![2019-09-30_11-51-23](https://user-images.githubusercontent.com/54129/65868493-a1b3b300-e378-11e9-8677-761f93f63f00.png)

How do I get back to the initial state and how do you navigate in the sidebar with a keyboard ? 

also, is there a way to have it word-wrap the lines with visual-line-mode or similar ?

**Comment by alphapapa** [comment]
That only happens to me if I press `M->` in the buffer.  It happens because it puts the point at the end of the last line, and the line is wider than the window.

Maybe a way could be devised to always put the point at the beginning of the line after a command, but, of course, that would make it impossible to view the end of lines that are wider than the window.

> How do I get back to the initial state 

It's just a window showing a buffer, like any other.  Put the point where you want it, e.g. with `C-a` or `M-<`.

> how do you navigate in the sidebar with a keyboard ?

It's just a window showing a buffer, like any other.  `C-n`, `C-p`, etc.  I also find `avy-goto-char-timer` helpful.

> also, is there a way to have it word-wrap the lines with visual-line-mode or similar ?

It's just a window showing a buffer, like any other.  You can enable whatever modes you like.

**Comment by alphapapa** [comment]
@maxandersen Do you have any more information about this?  Is it still happening?  Can you figure out what command you're doing that moves point to the end of the line?
